groups/urls.py
from django.urls import path
from groups import views
from posts import views as p_views

urlpatterns = [
    path('groups/', views.GroupsListView.as_view(), name='groups-list'),
    path('groups/create/', views.GroupCreateView.as_view(), name='group-create'),
    path('groups/<int:pk>/', views.GroupDetailView.as_view(), name='group-detailed'),
    path('groups/<int:pk>/create_post/', p_views.GroupPostCreateView.as_view(), name='group-create-post'),
    path('groups/<int:pk>/delete/', views.GroupDeleteView.as_view(), name='group-delete'),
    path('groups/<int:pk>/update/', views.GroupUpdateView.as_view(), name='group-update'),
    path('groups/<int:pk>/join/', views.MemberCreateView.as_view(), name='group-join'),
    path('groups/<int:pk>/leave/', views.MemberDeleteView.as_view(), name='group-leave'),
    path('channels/', views.ChannelListView.as_view(), name='channels-list'),
    path('channels/create/', views.ChannelCreateView.as_view(), name='channel-create'),
    path('channels/<int:pk>/update/', views.ChannelUpdateView.as_view(), name='channel-update'),
    path('channels/<int:pk>/delete/', views.ChannelDeleteView.as_view(), name='channel-delete'),
    path('channels/<int:pk>/', views.ChannelDetailView.as_view(), name='channel-detailed'),
    path('channels/<int:pk>/create_post/', p_views.ChannelPostCreateView.as_view(), name='channel-create-post'),
    path('channels/<int:pk>/join/', views.ViewerCreateView.as_view(), name='channel-join'),
    path("groups/<int:pk>/members/", views.MembersListView.as_view(), name='members-list'),
    path("channels/<int:pk>/viewers/", views.ViewersListView.as_view(), name='viewers-list'),

]

app_name = 'groups'

posts/urls.py
from django.urls import path
from posts import views


urlpatterns = [
    path("", views.PostsListView.as_view(), name="posts-list"),
    path("<int:pk>/", views.PostDetailView.as_view(), name="post-detailed"),
    path("<int:pk>/delete/", views.PostDeleteView.as_view(), name="delete-post"),
    path("<int:pk>/update/", views.PostUpdateView.as_view(), name="update-post"),
    path("<int:pk>/like/", views.LikeCreateView.as_view(), name="liking-post"),
    path("<int:pk>/comment/", views.CommentCreateView.as_view(), name="commenting-post"),
    path("<int:pk>/comment/delete/", views.CommentDeleteView.as_view(), name="comment-delete"),
    path("<int:pk>/comment/update/", views.CommentUpdateView.as_view(), name="comment-update"),
    path("<int:pk>/like/delete/", views.LikeDeleteView.as_view(), name="like-delete"),
    path("<int:pk>/repost/", views.RepostCreateView.as_view(), name="repost-create"),
    path("<int:pk>/repost/delete", views.RepostDeleteView.as_view(), name="repost-delete"),

]


app_name = "posts"

profiles/urls.py
from django.urls import path
from profiles import views
from posts import views as p_view


urlpatterns = [
    path('<int:pk>/', views.ProfileDetailView.as_view(), name="profile-detailed"),
    path("update/", views.ProfileUpdateView.as_view(), name="profile-update"),
    path("create_post/", p_view.ProfilePostCreateView.as_view(), name="create-post"),
    path("my_profile/", views.MyProfileDetailView.as_view(), name="my-profile"),
    path("<int:pk>/subscribe/", views.SubscriptionCreateView.as_view(), name="subscribe"),
    path("<int:pk>/unsubscribe/", views.SubscriptionDeleteView.as_view(), name="unsubscribe"),
    path("<int:pk>/send_friendrq/", views.FriendRequestCreateView.as_view(), name="friendrq"),
    path("<int:pk>/create_friendship/", views.FriendshipCreateView.as_view(), name="friendship"),
    path("<int:pk>/delete_friendrq/", views.FriendRequestDeleteView.as_view(), name="friendreq-delete"),
    path("users/", views.ProfilesListView.as_view(), name="profiles-list"),
    path("<int:pk>/delete_friendship/", views.FriendshipDeleteView.as_view(), name="friendship-delete"),

]

app_name = "profile"

social_media/urls.py
from django.contrib import admin
from django.urls import path, include
from social_media import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('posts.urls')),
    path('profile/', include('profiles.urls')),
    path('requests/', include('requests.urls')),
    path('groups_and_channels/', include('groups.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profiles/models.py
from django.db import models
from accounts.models import User

# Create your models here.


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="profile")
    pfp = models.ImageField(upload_to="users_pfp")
    username = models.CharField(max_length=80)
    bio = models.CharField(max_length=500, null=True, blank=True)
    status = models.CharField(max_length=60, null=True, blank=True)
    banner = models.ImageField(upload_to="users_banners", null=True, blank=True)

    def __str__(self):
        return self.username


class Friendship(models.Model):
    user1 = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name="friends_from")
    user2 = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name="friends_to")

    class Meta:
        unique_together = ("user1", "user2")

    def __str__(self):
        return f"{self.user1.username} is friends with {self.user2.username}"


class Subscriber(models.Model):
    subscriber = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name="subscriptions")
    account = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name="subscribers")

    def __str__(self):
        return f"{self.subscriber.username} subscribed to {self.account.username}"

profiles/forms.py
from django import forms
from profiles.models import Profile, Subscriber, Friendship
from requests.models import FriendRequest


class ProfileCreationForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['pfp', 'username', 'bio', 'status', 'banner']

    def __init__(self, *args, **kwargs):
        super(ProfileCreationForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({'class': "form-control mb-2"})

        self.fields["pfp"].widget.attrs.update({'class': "form-control mb-2", 'type': "file"})
        self.fields["banner"].widget.attrs.update({'class': "form-control mb-2", 'type': "file"})


class SubscriptionCreationForm(forms.ModelForm):
    class Meta:
        model = Subscriber
        fields = []


class FriendRequestCreationForm(forms.ModelForm):
    class Meta:
        model = FriendRequest
        fields = []


class FriendshipCreationForm(forms.ModelForm):
    class Meta:
        model = Friendship
        fields = []


class SearchForm(forms.Form):
    search = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control mb-2'}), required=False,
                             label="Search by username")

profiles/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import DetailView, UpdateView, CreateView, DeleteView, ListView
from profiles.models import Profile, Subscriber, Friendship
from profiles.forms import ProfileCreationForm, SubscriptionCreationForm, FriendRequestCreationForm, \
    FriendshipCreationForm, SearchForm
from requests.models import FriendRequest
from django.core.exceptions import ObjectDoesNotExist


# Create your views here.


class ProfileDetailView(DetailView):
    model = Profile
    context_object_name = "profile"
    template_name = "profile/profile_detailed.html"

    def get_watched_profile(self):
        user_pk = self.kwargs.get("pk")

        return get_object_or_404(Profile, pk=user_pk)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["subscription_form"] = SubscriptionCreationForm()
        context["friendrequest_form"] = FriendRequestCreationForm()
        context["friends_count"] = Friendship.objects.filter(
            Q(user1=self.get_watched_profile()) | Q(user2=self.get_watched_profile())).count()
        context["subscribers_count"] = self.get_watched_profile().subscribers.count()
        if self.request.user.is_authenticated:
            context["friendrequest"] = self.request.user.profile.friend_requests_send.filter(
                receiver=self.get_watched_profile())
            context["friendship"] = Friendship.objects.filter(
                Q(user1=self.request.user.profile, user2=self.get_watched_profile()) | Q(
                    user1=self.get_watched_profile(), user2=self.request.user.profile))
            context["subscription"] = self.request.user.profile.subscriptions.filter(
                account=self.get_watched_profile())

        return context


class ProfileUpdateView(LoginRequiredMixin, UpdateView):
    model = Profile
    context_object_name = "profile"
    form_class = ProfileCreationForm
    template_name = "profile/profile_update.html"
    success_url = reverse_lazy("profile:my-profile")

    def get_object(self, queryset=None):
        return self.request.user.profile


class MyProfileDetailView(LoginRequiredMixin, DetailView):
    model = Profile
    context_object_name = "my_profile"
    template_name = "profile/profile_detailed.html"

    def get_object(self, queryset=None):
        return self.request.user.profile

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["friends_count"] = Friendship.objects.filter(
            Q(user1=self.request.user.profile) | Q(user2=self.request.user.profile)).count()
        context["subscribers_count"] = self.request.user.profile.subscribers.count()

        return context


class SubscriptionCreateView(LoginRequiredMixin, CreateView):
    model = Subscriber
    context_object_name = "subscription"
    form_class = SubscriptionCreationForm

    def get_success_url(self):
        return reverse_lazy('profile:profile-detailed', kwargs={'pk': self.object.account.pk})

    def get_account(self):
        profile_pk = self.kwargs.get('pk')

        return get_object_or_404(Profile, pk=profile_pk)

    def form_valid(self, form):
        form.instance.subscriber = self.request.user.profile
        form.instance.account = self.get_account()

        return super().form_valid(form)


class SubscriptionDeleteView(LoginRequiredMixin, DeleteView):
    model = Subscriber
    template_name = "profile/subscription_delete_confirmation.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["user_pk"] = self.object.account.pk

        return context

    def get_success_url(self):
        return reverse_lazy('profile:profile-detailed', kwargs={'pk': self.object.account.pk})


class FriendRequestCreateView(LoginRequiredMixin, CreateView):
    model = FriendRequest
    context_object_name = "friend_request"
    form_class = FriendRequestCreationForm

    def get_success_url(self):
        return reverse_lazy('profile:profile-detailed', kwargs={'pk': self.object.receiver.pk})

    def get_receiver(self):
        receiver_pk = self.kwargs.get("pk")

        return get_object_or_404(Profile, pk=receiver_pk)

    def form_valid(self, form):
        form.instance.sender = self.request.user.profile
        form.instance.receiver = self.get_receiver()

        return super().form_valid(form)


class FriendRequestDeleteView(LoginRequiredMixin, DeleteView):
    model = FriendRequest
    template_name = "requests/friendrq_delete_confirmation.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["user_pk"] = self.object.receiver.pk

        return context

    def get_success_url(self):
        return reverse_lazy('profile:profile-detailed', kwargs={'pk': self.object.receiver.pk})


class FriendshipCreateView(LoginRequiredMixin, CreateView):
    model = Friendship
    context_object_name = "friendship"
    form_class = FriendshipCreationForm

    def get_success_url(self):
        return reverse_lazy('profile:profile-detailed', kwargs={'pk': self.object.user2.pk})

    def get_friend_request(self):
        friend_request_pk = self.kwargs.get("pk")

        return get_object_or_404(FriendRequest, pk=friend_request_pk)

    def form_valid(self, form):
        friend_request = self.get_friend_request()
        form.instance.user1 = self.request.user.profile
        form.instance.user2 = self.get_friend_request().sender
        friend_request.accepted = True
        friend_request.save()

        return super().form_valid(form)


class ProfilesListView(ListView):
    context_object_name = "profiles"
    model = Profile
    template_name = "profile/profiles_list.html"

    def get_queryset(self):
        queryset = super(ProfilesListView, self).get_queryset()

        profile_name = self.request.GET.get("search")
        if profile_name:
            queryset = queryset.filter(username__icontains=profile_name)

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = SearchForm(self.request.GET)
        if self.request.GET.get("search"):
            context["search"] = self.request.GET.get("search")

        return context


class FriendshipDeleteView(LoginRequiredMixin, DeleteView):
    model = Friendship
    template_name = 'profile/friendship_delete_confirmation.html'

    def form_valid(self, form):
        if self.object.user1 != self.request.user.profile:
            friend_request = FriendRequest.objects.filter(
                Q(sender=self.request.user.profile, receiver=self.object.user1) | Q(receiver=self.request.user.profile,
                                                                                    sender=self.object.user1)).first()
        else:
            friend_request = FriendRequest.objects.filter(
                Q(sender=self.request.user.profile, receiver=self.object.user2) | Q(receiver=self.request.user.profile,
                                                                                    sender=self.object.user2)).first()

        if friend_request:
            friend_request.delete()

        return super().form_valid(form)

    def get_success_url(self):
        if self.object.user1 != self.request.user.profile:
            return reverse_lazy("profile:profile-detailed", kwargs={'pk': self.object.user1.pk})
        else:
            return reverse_lazy("profile:profile-detailed", kwargs={'pk': self.object.user2.pk})

templates/profile/friendship_delete_confirmation.html
{% extends "base.html" %}
{% block title %}
    <title>Friendship Delete Confirmation</title>
{% endblock %}
{% block content %}
    <div class="container">
        {% include 'alerts.html' %}
        <div class="d-flex justify-content-center align-items-center">
            <form method="post" class="">
                {% csrf_token %}
                <h3>Are you sure?</h3>
                <button class="btn btn-light" type="submit"> Yes, delete </button>
                <a href="{% url 'groups:groups-list' %}" class="btn btn-secondary"> No </a>
            </form>
        </div>

    </div>
{% endblock %}

templates/profile/profile_detailed.html
{% extends "base.html" %}
{% block title %}
    {% if profile %}
        <title>{{ profile.username }}'s Profile</title>
    {% elif my_profile %}
        <title>{{ my_profile.username }}</title>
    {% endif %}
{% endblock %}

{% block content %}
    {% if profile %}
        <header class="container p-3 mb-3" style='
                {% if profile.banner %} 
                    background: no-repeat url("{{ profile.banner.url }}") center; 
                {% else %} 
                    background: no-repeat linear-gradient(90deg, rgba(131,58,180,1) 0%, rgba(253,29,29,1) 50%, rgba(252,176,69,1) 100%); 
                {% endif %}background-size:cover;'>
            <div class="">
                    <div class="align-items-center d-flex m-3">
                        {% if profile.pfp %}
                    <img src="{{ profile.pfp.url }}" alt="Profile Picture" class="me-3"
                         style="border-radius: 50%; width: 200px; height:200px; border: 2px grey solid">
                {% endif %}
                <div>
                    <h1 style="text-shadow: 10px 5px 5px black;">{{ profile.username }}</h1>
                    <h5 style="text-shadow: 10px 5px 5px black;">{{ profile.bio }}</h5>
                </div>
                </div>
                <p>{{ friends_count }} friends</p>
                <p>{{ subscribers_count }} subscribers</p>
        </header>
                <div class="d-flex container">
                    {% if not subscription %}
                        <form action="{% url 'profile:subscribe' pk=profile.pk %}" method="POST">
                            {% csrf_token %}
                            {{ subscription_form.as_div }}
                            <button type="submit" class="btn btn-danger">Subscribe</button>
                        </form>
                    {% else %}
                        <a href="{% url "profile:unsubscribe" pk=subscription.first.pk %}"
                           class="btn btn-secondary">Unsubscribe</a>
                    {% endif %}
                {% if friendship %}
                    <a href="{% url "profile:friendship-delete" pk=friendship.first.pk %}" class="btn btn-success">You are friends</a>
                    {% else %}
                    {% if not friendrequest %}
                        <form action="{% url 'profile:friendrq' pk=profile.pk %}" method="POST">
                            {% csrf_token %}
                            {{ subscription_form.as_div }}
                            <button type="submit" class="btn btn-success">Send Friend Request</button>
                        </form>
                    {% elif friendrequest %}
                        <a href="{% url "profile:friendreq-delete" pk=friendrequest.first.pk %}"
                           class="btn btn-warning">Delete
                            Friend Request</a>
                    {% endif %}
                {% endif %}
                </div>
                <div class="container">
                    {% for post in profile.profile_posts.all %}
                        {% include "post.html" %}
                    {% endfor %}
                </div>
        
        
    {% endif %}
    {% if my_profile %}

        <header class="container p-3 mb-3" style='
                {% if my_profile.banner %} 
                    background: no-repeat url("{{ my_profile.banner.url }}") center; 
                {% else %} 
                    background: no-repeat linear-gradient(90deg, rgba(131,58,180,1) 0%, rgba(253,29,29,1) 50%, rgba(252,176,69,1) 100%); 
                {% endif %}background-size:cover;'>

            {% if my_profile.pfp %}
                <div class="align-items-center d-flex m-3">
                <img src="{{ my_profile.pfp.url }}" alt="Profile Picture" class="me-3"
                     style="border-radius: 50%; width: 200px; height:200px; border: 2px grey solid">
            {% endif %}
            <div>
                <h1 style="text-shadow: 10px 5px 5px black;">{{ my_profile.username }}</h1>
                <h5 style="text-shadow: 10px 5px 5px black;">{{ my_profile.bio }}</h5>
                <h5>{{ friends_count }} friends</h5>
                <h5>{{ subscribers_count }} subscribers</h5>
            </div>
            </div>
        </header>
        <div class="container">
            <a href="{% url 'profile:profile-update' %}" class="btn btn-primary">Edit Profile</a>

        </div>
        <div class="container">
            {% for post in my_profile.profile_posts.all %}
                {% include "post.html" %}
            {% endfor %}
        </div>
    {% endif %}


{% endblock %}

templates/profile/profile_update.html
{% extends 'base.html' %}
{% block title %}
	<title>Profile update</title>
{% endblock %}
{% block content %}
    <div class="container">
    <form action="{% url "profile:profile-update" %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_div }}
        <button type="submit" class="btn btn-success">Submit</button>
    </form> 
    </div>
    
{% endblock %}

templates/profile/profiles_list.html
{% extends 'base.html' %}
{% block title %}
	<title>Users</title>
{% endblock %}
{% block content %}
	<div class="container">
    <form method="GET">
      {{ form.as_div }}
        <button type="submit" class="btn btn-primary mt-3">Search</button>
    </form>
    <div class="row">
    {% if search %}
        {% for profile in profiles %}
            {% include "profile.html" %} 
        {% endfor %}
    {% endif %}
    </div>
    </div>
{% endblock %}

templates/profile/subscription_delete_confirmation.html
{% extends 'base.html' %}

{% block content %}
   <div class="container">
   {% include 'alerts.html' %}
        <div class="d-flex justify-content-center align-items-center">
            <form method="post" class="">
          {% csrf_token %}
           <h3>Are you sure?</h3>
           <button class="btn btn-light" type="submit"> Yes, delete </button>
           <a href="{% url 'profile:profile-detailed' pk=user_pk %}" class="btn btn-secondary"> No </a>
       </form>
        </div>

   </div>

{% endblock %}