posts/urls.py
from django.urls import path
from posts import views


urlpatterns = [
    path("", views.PostsListView.as_view(), name="posts-list"),
    path("<int:pk>/", views.PostDetailView.as_view(), name="post-detailed"),
    path("<int:pk>/delete/", views.PostDeleteView.as_view(), name="delete-post"),
    path("<int:pk>/update/", views.PostUpdateView.as_view(), name="update-post"),
    path("<int:pk>/like/", views.LikeCreateView.as_view(), name="liking-post"),
    path("<int:pk>/comment/", views.CommentCreateView.as_view(), name="commenting-post"),
    path("<int:pk>/comment/delete/", views.CommentDeleteView.as_view(), name="comment-delete"),
    path("<int:pk>/comment/update/", views.CommentUpdateView.as_view(), name="comment-update"),
    path("<int:pk>/like/delete/", views.LikeDeleteView.as_view(), name="like-delete"),
    path("<int:pk>/repost/", views.RepostCreateView.as_view(), name="repost-create"),
    path("<int:pk>/repost/delete", views.RepostDeleteView.as_view(), name="repost-delete"),

]


app_name = "posts"

profiles/urls.py
from django.urls import path
from profiles import views
from posts import views as p_view


urlpatterns = [
    path('<int:pk>/', views.ProfileDetailView.as_view(), name="profile-detailed"),
    path("update/", views.ProfileUpdateView.as_view(), name="profile-update"),
    path("create_post/", p_view.ProfilePostCreateView.as_view(), name="create-post"),
    path("my_profile/", views.MyProfileDetailView.as_view(), name="my-profile"),
    path("<int:pk>/subscribe/", views.SubscriptionCreateView.as_view(), name="subscribe"),
    path("<int:pk>/unsubscribe/", views.SubscriptionDeleteView.as_view(), name="unsubscribe"),
    path("<int:pk>/send_friendrq/", views.FriendRequestCreateView.as_view(), name="friendrq"),
    path("<int:pk>/create_friendship/", views.FriendshipCreateView.as_view(), name="friendship"),
    path("<int:pk>/delete_friendrq/", views.FriendRequestDeleteView.as_view(), name="friendreq-delete"),
    path("users/", views.ProfilesListView.as_view(), name="profiles-list"),
    path("<int:pk>/delete_friendship/", views.FriendshipDeleteView.as_view(), name="friendship-delete"),

]

app_name = "profile"

social_media/urls.py
from django.contrib import admin
from django.urls import path, include
from social_media import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('posts.urls')),
    path('profile/', include('profiles.urls')),
    path('requests/', include('requests.urls')),
    path('groups_and_channels/', include('groups.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/models.py
from django.db import models
from profiles.models import Profile
from groups.models import Group, Channel
from django.contrib.auth.models import User


# Create your models here.

class Post(models.Model):
    TYPE_CHOICES = {
        "profile": "Profile",
        "group": "Group",
        "channel": "Channel"
    }

    title = models.CharField(max_length=50)
    description = models.TextField()
    media = models.FileField(upload_to="posts_media", null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name="posts")
    type = models.CharField(choices=TYPE_CHOICES, max_length=8)
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name="profile_posts", null=True, blank=True)
    group = models.ForeignKey(Group, on_delete=models.CASCADE, related_name="group_posts", null=True, blank=True)
    channel = models.ForeignKey(Channel, on_delete=models.CASCADE, related_name="channel_posts", null=True, blank=True)

    def save(self, *args, **kwargs):
        if not self.profile and not self.group and not self.channel:
            raise ValueError("Post must have a relation")
        return super().save(*args, **kwargs)


    def __str__(self):
        return self.title

    class Meta:
        ordering = ["-created_at"]


class Comment(models.Model):
    related_post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments_on_post")
    content = models.CharField(max_length=250)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(Profile, on_delete=models.DO_NOTHING, related_name="comments")

    def __str__(self):
        return f"Comment by {self.created_by.username} under {self.related_post.title} post"


class Like(models.Model):
    user = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name="likes")
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="likes")

    def __str__(self):
        return f"{self.user.username} liked {self.post.title} post"


class Repost(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="reposts")
    user = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name="reposts")
    text = models.CharField(max_length=80, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username} reposted {self.post.title}"

posts/forms.py
from django import forms

from posts.models import Post, Like, Comment, Repost


class PostCreationForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["title", "description", "media"]

    def __init__(self, *args, **kwargs):
        super(PostCreationForm, self).__init__(*args, **kwargs)

        for field in self.fields:
            self.fields[field].widget.attrs.update({'class': "form-control mb-2"})

        self.fields["media"].widget.attrs.update({'class': "form-control mb-2", "type": "file"})


class PostUpdateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["title", "description"]

    def __init__(self, *args, **kwargs):
        super(PostUpdateForm, self).__init__(*args, **kwargs)

        for field in self.fields:
            self.fields[field].widget.attrs.update({'class': "form-control mb-2"})


class LikeCreationForm(forms.ModelForm):
    class Meta:
        model = Like
        fields = []


class CommentCreationForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["content"]
        widgets = {
            "content": forms.Textarea(attrs={'class': 'form-control mb-2'}),
        }


class RepostCreationForm(forms.ModelForm):
    class Meta:
        model = Repost
        fields = ["text"]
        widgets = {
            "text": forms.Textarea(attrs={'class': 'form-control mb-2'}),
        }

posts/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ObjectDoesNotExist, PermissionDenied
from django.db import models
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView

from groups.models import Group, Channel
from posts.forms import PostCreationForm, PostUpdateForm, LikeCreationForm, CommentCreationForm, RepostCreationForm
from posts.models import Post, Comment, Like, Repost
from posts.mixins import UserIsOwnerMixin, ObjectExistMixin, UserIsNotLikeOwnerMixin, UsersActionMixin, \
    UserIsNotOwnerMixin
from profiles.models import Profile


# Create your views here.


class PostsListView(ListView):
    model = Post
    paginate_by = 10
    context_object_name = "posts"
    template_name = "posts/posts_list.html"

    def get_queryset(self):
        queryset = super(PostsListView, self).get_queryset()
        try:
            profile = self.request.user.profile
        except AttributeError:
            return queryset
        groups = Group.objects.filter(members__user=profile)
        channels = Channel.objects.filter(viewers__user=profile)
        friends = Profile.objects.filter(models.Q(friends_from__user1=profile) | models.Q(friends_to__user2=profile))
        subscriptions = Profile.objects.filter(subscriptions__subscriber=profile)

        posts = Post.objects.filter(
            models.Q(group__in=groups) | models.Q(channel__in=channels) | models.Q(profile__in=friends) | models.Q(profile__in=subscriptions)).distinct()

        return posts


class PostDetailView(DetailView):
    model = Post
    context_object_name = "post"
    template_name = "posts/post_detailed.html"

    def get_watched_post(self):
        post_pk = self.kwargs.get("pk")

        return get_object_or_404(Post, pk=post_pk)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["liking_form"] = LikeCreationForm()
        context["comment_form"] = CommentCreationForm()
        context["repost_form"] = RepostCreationForm()
        context["comments"] = get_object_or_404(Post, pk=self.kwargs.get("pk")).comments_on_post.all()
        if self.request.user.is_authenticated:
            context["repost"] = self.request.user.profile.reposts.filter(post=self.get_watched_post())
            context["like"] = self.request.user.profile.likes.filter(post=self.get_watched_post())
        context["likes_count"] = self.object.likes.count()
        context["repost_count"] = self.object.reposts.count()

        return context


class ProfilePostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    success_url = reverse_lazy("profile:my-profile")
    form_class = PostCreationForm
    template_name = "posts/post_creation_form.html"

    def form_valid(self, form):
        form.instance.created_by = self.request.user.profile
        form.instance.profile = self.request.user.profile
        form.instance.type = "profile"

        return super().form_valid(form)


class GroupPostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    form_class = PostCreationForm
    template_name = "posts/post_creation_form.html"

    def form_valid(self, form):
        form.instance.created_by = self.request.user.profile
        form.instance.group = get_object_or_404(Group, pk=self.kwargs.get("pk"))
        form.instance.type = "group"

        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy("groups:group-detailed", kwargs={"pk": self.kwargs.get("pk")})


class ChannelPostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    form_class = PostCreationForm
    template_name = "posts/post_creation_form.html"

    def get_success_url(self):
        return reverse_lazy("groups:channel-detailed", kwargs={"pk": self.kwargs.get("pk")})

    def form_valid(self, form):
        form.instance.created_by = self.request.user.profile
        form.instance.channel = get_object_or_404(Channel, pk=self.kwargs.get("pk"))
        form.instance.type = "channel"

        return super().form_valid(form)


class PostDeleteView(LoginRequiredMixin, UserIsOwnerMixin, DeleteView):
    model = Post
    template_name = "posts/post_delete_confirmation.html"
    success_url = reverse_lazy("posts:posts-list")


class PostUpdateView(LoginRequiredMixin, UserIsOwnerMixin, UpdateView):
    model = Post
    form_class = PostUpdateForm
    context_object_name = "post"
    template_name = "posts/post_update_form.html"

    def get_success_url(self):
        return reverse_lazy("posts:post-detailed", kwargs={"pk": self.object.pk})


class LikeCreateView(LoginRequiredMixin, UserIsNotLikeOwnerMixin, ObjectExistMixin, CreateView):
    model = Like
    form_class = LikeCreationForm

    def get_post(self):
        post_pk = self.kwargs.get("pk")

        return get_object_or_404(Post, pk=post_pk)

    def get_success_url(self):
        return reverse_lazy("posts:post-detailed", kwargs={"pk": self.object.post.pk})

    def form_valid(self, form):
        form.instance.post = self.get_post()
        form.instance.user = self.request.user.profile

        return super().form_valid(form)


class LikeDeleteView(LoginRequiredMixin, UsersActionMixin, DeleteView):
    model = Like

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["post_pk"] = self.object.post.pk

        return context

    def get_post(self):
        post_pk = self.kwargs.get("pk")

        return get_object_or_404(Post, pk=post_pk)

    def get_success_url(self):
        return reverse_lazy("posts:post-detailed", kwargs={"pk": self.object.post.pk})


class CommentCreateView(LoginRequiredMixin, CreateView):
    model = Comment
    form_class = CommentCreationForm

    def get_post(self):
        post_pk = self.kwargs.get("pk")

        return get_object_or_404(Post, pk=post_pk)

    def get_success_url(self):
        return reverse_lazy("posts:post-detailed", kwargs={"pk": self.object.related_post.pk})

    def form_valid(self, form):
        form.instance.created_by = self.request.user.profile
        form.instance.related_post = self.get_post()

        return super().form_valid(form)


class CommentUpdateView(LoginRequiredMixin, UserIsOwnerMixin, UpdateView):
    model = Comment
    template_name = "posts/comment_update_form.html"
    form_class = CommentCreationForm

    def get_success_url(self):
        return reverse_lazy("posts:post-detailed", kwargs={"pk": self.object.related_post.pk})


class CommentDeleteView(LoginRequiredMixin, UserIsOwnerMixin, DeleteView):
    model = Comment
    template_name = "posts/comment_delete_confirmation.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["post_pk"] = self.object.related_post.pk

        return context

    def get_success_url(self):
        return reverse_lazy("posts:post-detailed", kwargs={"pk": self.object.related_post.pk})


class RepostCreateView(LoginRequiredMixin, CreateView):
    model = Repost
    form_class = RepostCreationForm

    def get_post(self):
        post_pk = self.kwargs.get("pk")

        return get_object_or_404(Post, pk=post_pk)

    def get_success_url(self):
        return reverse_lazy("posts:post-detailed", kwargs={"pk": self.object.post.pk})

    def form_valid(self, form):
        if self.request.user.profile == self.get_post().created_by:
            raise PermissionDenied("You can't repost your own post.")
        form.instance.user = self.request.user.profile
        form.instance.post = self.get_post()

        return super().form_valid(form)


class RepostDeleteView(LoginRequiredMixin, UsersActionMixin, DeleteView):
    model = Repost

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["post_pk"] = self.object.post.pk

        return context

    def get_post(self):
        post_pk = self.kwargs.get("pk")

        return get_object_or_404(Post, pk=post_pk)

    def get_success_url(self):
        return reverse_lazy("posts:post-detailed", kwargs={"pk": self.object.post.pk})

templates/posts/comment_delete_confirmation.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        {% include 'alerts.html' %}
        <div class="d-flex justify-content-center align-items-center">
            <form method="post" class="">
                {% csrf_token %}
                <h3>Are you sure?</h3>
                <button class="btn btn-light" type="submit"> Yes, delete </button>
                <a href="{% url 'posts:post-detailed' pk=post_pk %}" class="btn btn-secondary"> No </a>
            </form>
        </div>

    </div>

{% endblock %}

templates/posts/comment_update_form.html
{% extends "base.html" %}
{% block title %}
	<title>Comment Update</title>
{% endblock %}
{% block content %}
	<div class="container">
        <form method="POST">
            {% csrf_token %}
            {{ form.as_div }}
            <button type="submit" class="btn btn-success">Update Comment</button>
        </form>
    </div>
{% endblock %}

templates/posts/post_creation_form.html
{% extends "base.html" %}
{% block title %}
	<title>Post Creation</title>
{% endblock %}
{% block content %}
	<div class="container">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_div }}
            <button type="submit" class="btn btn-success">Create Post</button>
        </form>
    </div>
{% endblock %}

templates/posts/post_delete_confirmation.html
{% extends "base.html" %}
{% block title %}
	<title>Delete Confirmation</title>
{% endblock %}
{% block content %}
    <div class="container">
        {% include 'alerts.html' %}
        <div class="d-flex justify-content-center align-items-center">
            <form method="post" class="">
                {% csrf_token %}
                <h3>Are you sure?</h3>
                <button class="btn btn-light" type="submit"> Yes, delete </button>
                <a href="{% url 'posts:posts-list' %}" class="btn btn-secondary"> No </a>
            </form>
        </div>

    </div>
{% endblock %}

templates/posts/post_detailed.html
{% extends "base.html" %}
{% block title %}
	<title>{{ post.title }}</title>
{% endblock %}
{% block content %}
	<div class="container">
    <div class="row">
        <div class="col-12 col-md-7">
        <h2>{{ post.title }}</h2>
        {% if post.media %}
        <img class="img-fluid" src="{{ post.media.url }}" alt="Post Image" style="max-height: 500px">
        {% endif %}
        <p>{{ post.description }}</p>
        <p>Posted at: {{ post.created_at }}</p>
        <p></p>
        <a href="{% url 'profile:profile-detailed' pk=post.created_by.pk %}">{{ post.created_by }}</a>
        {% if post.created_by == request.user.profile %}
        <a href="{% url 'posts:delete-post' pk=post.pk %}" class="btn btn-danger m-2">Delete Post</a>
        <a href="{% url 'posts:update-post' pk=post.pk %}" class="btn btn-primary m-2">Update Post</a>

        {% endif %}

        {% if user.is_authenticated %}
            <div class="d-flex ">
        {% if not like %}
        <form action="{% url "posts:liking-post" pk=post.pk %}" method="POST">
            {% csrf_token %}
            <button type="submit" class="btn btn-secondary "><i class="bi bi-heart"></i> {{ likes_count }}</button>
        </form>
        {% else %}
        <form action="{% url "posts:like-delete" pk=like.first.pk %}" method="POST">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger"><i class="bi bi-heart-fill"></i> {{ likes_count }}</button>
        </form>
        {% endif %}
        {% if not repost %}
        <!-- Button trigger modal -->
        <button type="button" class="btn btn-success ms-3" data-bs-toggle="modal" data-bs-target="#exampleModal">
            <i class="bi bi-repeat"></i> {{ repost_count }}
        </button>

        <!-- Modal -->
        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h1 class="modal-title fs-5" id="exampleModalLabel">Modal title</h1>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <form action="{% url "posts:repost-create" pk=post.pk %}" method="POST">
                        <div class="modal-body">
                            {% csrf_token %}
                            {{ repost_form.as_div }}
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-success">Repost</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        {% else %}
        <form action="{% url "posts:repost-delete" pk=repost.first.pk %}" method="POST">
            {% csrf_token %}
            <button type="submit" class="btn btn-success ms-3">
                <i class="bi bi-repeat"></i> {{ repost_count }}
</button>
        </form>
        {% endif %}
</div>
        {% endif %}
        </div>
    
    <div class="col-12 col-md-5">
        <form action="{% url 'posts:commenting-post' pk=post.pk %}" method="POST">
            {% csrf_token %}
            {{ comment_form.as_div }}
            <button type="submit" class="btn btn-success">Create Comment</button>
        </form>
        
        {% if comments %}
        {% for comment in comments %}
        <div class="card mt-3">
            <div class="card-body">
                {% if request.user.profile == comment.created_by %}
                <a href="{% url 'posts:comment-delete' pk=comment.pk %}" class="btn btn-danger"><i
                        class="bi bi-trash-fill"></i></a>
                <a href="{% url "posts:comment-update" pk=comment.pk %}" class="btn btn-primary"><i
                        class="bi bi-pencil-square"></i></a>
                {% endif %}

                <h5 class="card-title">{{ comment.created_by }}</h5>
                <p class="card-text">{{ comment.content }}</p>
                <p class="card-text mt-4">This comment was added at {{ comment.created_at }}</p>

            </div>
        </div>
        {% endfor %}

        {% endif %}
    </div>
    </div>
    </div>
{% endblock %}

templates/posts/post_update_form.html
{% extends 'base.html' %}
{% block title %}
	<title>Post Update</title>
{% endblock %}
{% block content %}
	<div class="container">
        <form action="{% url 'posts:update-post' pk=post.pk %}" method="POST">
            {% csrf_token %}
            {{ form.as_div }}
            <button type="submit" class="btn btn-success">Update Post</button>
        </form>
    </div>
{% endblock %}

templates/posts/posts_list.html
{% extends "base.html" %}
{% block title %}
	<title>Posts List</title>
{% endblock %}

{% block content %}
{% load static %}
    {% if user.is_authenticated %}
	<div class="container">
        <div class="row">
            <div class="col-2"></div>
            <div class="col-8">
                {% for post in posts %}
                        {% include "post.html" %}
                
                {% endfor %}
                {% for page_num in page_obj.paginator.page_range %}
                    <a href="?page={{ page_num }}" class="d-inline-block">{{ page_num }}</a>
                {% endfor %}
            </div>
            <div class="col-2"></div>

        </div>
    </div>
    {% else %}
    <h2>Authorize to see content</h2>
    {% endif %}
{#    <script>#}
{#    function ajaxSend(){#}
{#        fetch('')#}
{#            .then(response => response.text())#}
{#            .then(data => {#}
{#                alert(data)#}
{#            })#}
{#            .catch(error => console.log('Error:', error));#}
{#    }#}
{#    </script>#}
{% endblock %}