groups/urls.py
from django.urls import path
from groups import views
from posts import views as p_views

urlpatterns = [
    path('groups/', views.GroupsListView.as_view(), name='groups-list'),
    path('groups/create/', views.GroupCreateView.as_view(), name='group-create'),
    path('groups/<int:pk>/', views.GroupDetailView.as_view(), name='group-detailed'),
    path('groups/<int:pk>/create_post/', p_views.GroupPostCreateView.as_view(), name='group-create-post'),
    path('groups/<int:pk>/delete/', views.GroupDeleteView.as_view(), name='group-delete'),
    path('groups/<int:pk>/update/', views.GroupUpdateView.as_view(), name='group-update'),
    path('groups/<int:pk>/join/', views.MemberCreateView.as_view(), name='group-join'),
    path('groups/<int:pk>/leave/', views.MemberDeleteView.as_view(), name='group-leave'),
    path('channels/', views.ChannelListView.as_view(), name='channels-list'),
    path('channels/create/', views.ChannelCreateView.as_view(), name='channel-create'),
    path('channels/<int:pk>/update/', views.ChannelUpdateView.as_view(), name='channel-update'),
    path('channels/<int:pk>/delete/', views.ChannelDeleteView.as_view(), name='channel-delete'),
    path('channels/<int:pk>/', views.ChannelDetailView.as_view(), name='channel-detailed'),
    path('channels/<int:pk>/create_post/', p_views.ChannelPostCreateView.as_view(), name='channel-create-post'),
    path('channels/<int:pk>/join/', views.ViewerCreateView.as_view(), name='channel-join'),
    path("groups/<int:pk>/members/", views.MembersListView.as_view(), name='members-list'),
    path("channels/<int:pk>/viewers/", views.ViewersListView.as_view(), name='viewers-list'),

]

app_name = 'groups'

posts/urls.py
from django.urls import path
from posts import views


urlpatterns = [
    path("", views.PostsListView.as_view(), name="posts-list"),
    path("<int:pk>/", views.PostDetailView.as_view(), name="post-detailed"),
    path("<int:pk>/delete/", views.PostDeleteView.as_view(), name="delete-post"),
    path("<int:pk>/update/", views.PostUpdateView.as_view(), name="update-post"),
    path("<int:pk>/like/", views.LikeCreateView.as_view(), name="liking-post"),
    path("<int:pk>/comment/", views.CommentCreateView.as_view(), name="commenting-post"),
    path("<int:pk>/comment/delete/", views.CommentDeleteView.as_view(), name="comment-delete"),
    path("<int:pk>/comment/update/", views.CommentUpdateView.as_view(), name="comment-update"),
    path("<int:pk>/like/delete/", views.LikeDeleteView.as_view(), name="like-delete"),
    path("<int:pk>/repost/", views.RepostCreateView.as_view(), name="repost-create"),
    path("<int:pk>/repost/delete", views.RepostDeleteView.as_view(), name="repost-delete"),

]


app_name = "posts"

profiles/urls.py
from django.urls import path
from profiles import views
from posts import views as p_view


urlpatterns = [
    path('<int:pk>/', views.ProfileDetailView.as_view(), name="profile-detailed"),
    path("update/", views.ProfileUpdateView.as_view(), name="profile-update"),
    path("create_post/", p_view.ProfilePostCreateView.as_view(), name="create-post"),
    path("my_profile/", views.MyProfileDetailView.as_view(), name="my-profile"),
    path("<int:pk>/subscribe/", views.SubscriptionCreateView.as_view(), name="subscribe"),
    path("<int:pk>/unsubscribe/", views.SubscriptionDeleteView.as_view(), name="unsubscribe"),
    path("<int:pk>/send_friendrq/", views.FriendRequestCreateView.as_view(), name="friendrq"),
    path("<int:pk>/create_friendship/", views.FriendshipCreateView.as_view(), name="friendship"),
    path("<int:pk>/delete_friendrq/", views.FriendRequestDeleteView.as_view(), name="friendreq-delete"),
    path("users/", views.ProfilesListView.as_view(), name="profiles-list"),
    path("<int:pk>/delete_friendship/", views.FriendshipDeleteView.as_view(), name="friendship-delete"),

]

app_name = "profile"

social_media/urls.py
from django.contrib import admin
from django.urls import path, include
from social_media import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('posts.urls')),
    path('profile/', include('profiles.urls')),
    path('requests/', include('requests.urls')),
    path('groups_and_channels/', include('groups.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

groups/models.py
from django.db import models
from profiles.models import Profile

# Create your models here.


class Group(models.Model):
    group_picture = models.ImageField(upload_to="group_pictures", null=True, blank=True)
    title = models.CharField(max_length=80)
    description = models.CharField(max_length=500)
    created_by = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name="groups")
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


class Member(models.Model):
    user = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name="memberships")
    is_admin = models.BooleanField(default=False)
    group = models.ForeignKey(Group, on_delete=models.CASCADE, related_name="members")

    def __str__(self):
        return f"{self.user.username} is member of {self.group.title} group"

    class Meta:
        unique_together = ("user", "group")


class Channel(models.Model):
    channel_picture = models.ImageField(upload_to="channel_pictures", null=True, blank=True)
    title = models.CharField(max_length=80)
    description = models.CharField(max_length=500)
    created_by = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name="communities")
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


class Viewer(models.Model):
    user = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name="views")
    is_admin = models.BooleanField(default=False)
    channel = models.ForeignKey(Channel, on_delete=models.CASCADE, related_name="viewers")

    def __str__(self):
        return f"{self.user.username} views {self.channel.title}"

    class Meta:
        unique_together = ("user", "channel")

groups/forms.py
from django.forms import ModelForm
from groups.models import Group, Member, Channel, Viewer


class GroupCreationForm(ModelForm):
    class Meta:
        model = Group
        fields = ["title", "description", "group_picture"]

    def __init__(self, *args, **kwargs):
        super(GroupCreationForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs = {'class': 'form-control mb-2'}

        self.fields['group_picture'].widget.attrs = {'class': 'form-control mb-2', 'type': 'file'}


class MemberCreationForm(ModelForm):
    class Meta:
        model = Member
        fields = []


class ViewerCreationForm(ModelForm):
    class Meta:
        model = Viewer
        fields = []


class ChannelCreationForm(ModelForm):
    class Meta:
        model = Channel
        fields = ['title', 'description', "channel_picture"]

    def __init__(self, *args, **kwargs):
        super(ChannelCreationForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs = {'class': 'form-control mb-2'}

        self.fields['channel_picture'].widget.attrs = {'class': 'form-control mb-2', 'type': 'file'}

groups/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
from groups.models import Group, Member, Channel, Viewer
from groups.forms import GroupCreationForm, MemberCreationForm, ChannelCreationForm, ViewerCreationForm
from posts.models import Post


# Create your views here.

class GroupsListView(ListView):
    model = Group
    context_object_name = "groups"
    template_name = "groups/groups_list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["join_form"] = MemberCreationForm()

        return context


class GroupDetailView(DetailView):
    model = Group
    context_object_name = "group"
    template_name = "groups/group_detailed.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["members"] = Member.objects.filter(group=self.object)
        context["posts"] = Post.objects.filter(type="group", group=self.object)

        return context


class GroupCreateView(LoginRequiredMixin, CreateView):
    model = Group
    form_class = GroupCreationForm
    template_name = "groups/group_creation_page.html"
    success_url = reverse_lazy("groups:groups-list")

    def form_valid(self, form):
        form.instance.created_by = self.request.user.profile
        group = form.save()

        Member.objects.create(user=self.request.user.profile, group=group).save()
        group.save()

        return super().form_valid(form)


class GroupUpdateView(LoginRequiredMixin, UpdateView):
    model = Group
    template_name = "groups/group_creation_page.html"

    def get_success_url(self):
        return reverse_lazy("groups:groups-detail", kwargs={"pk": self.object.pk})


class GroupDeleteView(LoginRequiredMixin, DeleteView):
    model = Group
    template_name = "groups/group_delete_confirmation.html"
    success_url = reverse_lazy("groups:groups-list")


class MemberCreateView(LoginRequiredMixin, CreateView):
    model = Member
    form_class = MemberCreationForm

    def get_group(self):
        group_pk = self.kwargs.get("pk")

        return get_object_or_404(Group, pk=group_pk)

    def form_valid(self, form):
        form.instance.user = self.request.user.profile
        form.instance.group = self.get_group()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy("groups:group-detailed", kwargs={"pk": self.kwargs.get("pk")})


class MemberDeleteView(LoginRequiredMixin, DeleteView):
    model = Member
    template_name = "groups/group_leaving_confirmation.html"
    success_url = reverse_lazy("groups:groups-list")
    context_object_name = "member"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["group_pk"] = self.kwargs.get("pk")

        return context

    def get_object(self, queryset=None):
        obj = Member.objects.get(user=self.request.user.profile, group=self.kwargs.get("pk"))

        return obj


class ChannelListView(ListView):
    model = Channel
    context_object_name = "channels"
    template_name = "groups/channels_list.html"


class ChannelDetailView(DetailView):
    model = Channel
    context_object_name = "channel"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["viewers"] = Viewer.objects.filter(channel=self.object)
        context["joining"] = ViewerCreationForm()
        context['current_viewer'] = self.request.user.profile.views.filter(channel=self.object).first()
        context['posts'] = Post.objects.filter(type="channel", channel=self.object)

        return context


class ChannelCreateView(LoginRequiredMixin, CreateView):
    model = Channel
    form_class = ChannelCreationForm
    template_name = "groups/channel_creation_page.html"
    success_url = reverse_lazy("groups:channels-list")

    def form_valid(self, form):
        form.instance.created_by = self.request.user.profile
        channel = form.save()

        Viewer.objects.create(user=self.request.user.profile, channel=channel, is_admin=True).save()
        channel.save()

        return super().form_valid(form)


class ChannelUpdateView(LoginRequiredMixin, UpdateView):
    model = Channel
    form_class = ChannelCreationForm
    context_object_name = "channel"
    template_name = "groups/channel_creation_page.html"

    def get_success_url(self):
        return reverse_lazy("groups:channel-detailed", pk=self.kwargs.get("pk"))


class ChannelDeleteView(LoginRequiredMixin, DeleteView):
    model = Channel
    template_name = "groups/channel_delete_confirmation.html"
    success_url = reverse_lazy("groups:channels-list")


class ViewerCreateView(LoginRequiredMixin, CreateView):
    model = Viewer
    form_class = ViewerCreationForm

    def get_channel(self):
        channel_pk = self.kwargs.get("pk")

        return get_object_or_404(Channel, pk=channel_pk)

    def form_valid(self, form):
        form.instance.user = self.request.user.profile
        form.instance.channel = self.get_channel()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy("groups:channel-detailed", kwargs={"pk": self.kwargs.get("pk")})


class ViewerDeleteView(LoginRequiredMixin, DeleteView):
    model = Viewer
    template_name = "groups/group_leaving_confirmation.html"
    success_url = reverse_lazy("groups:channels-list")
    context_object_name = "viewer"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["channel_pk"] = self.kwargs.get("pk")

        return context

    def get_object(self, queryset=None):
        obj = Viewer.objects.get(user=self.request.user.profile, channel=self.kwargs.get("pk"))

        return obj


class MembersListView(ListView):
    model = Member
    context_object_name = "members"
    template_name = "groups/members_list_view.html"

    def get_queryset(self):
        queryset = super(MembersListView, self).get_queryset()
        queryset = queryset.filter(group=Group.objects.get(pk=self.kwargs.get("pk")))

        return queryset


class ViewersListView(ListView):
    model = Viewer
    context_object_name = "viewers"
    template_name = "groups/viewers_list_view.html"

    def get_queryset(self):
        queryset = super(ViewersListView, self).get_queryset()
        queryset = queryset.filter(channel=Channel.objects.get(pk=self.kwargs.get("pk")))

        return queryset

templates/groups/channel_creation_page.html
{% extends 'base.html' %}
{% block title %}
	<title>Community Creation</title>
{% endblock %}
{% block content %}
	<div class="container">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_div }}
        <button type="submit" class="btn btn-success">Create Channel</button>
    </form>
    </div>
{% endblock %}

templates/groups/channel_delete_confirmation.html
{% extends "base.html" %}
{% block title %}
    <title>Delete Confirmation</title>
{% endblock %}
{% block content %}
    <div class="container">
        {% include 'alerts.html' %}
        <div class="d-flex justify-content-center align-items-center">
            <form method="post" class="">
                {% csrf_token %}
                <h3>Are you sure?</h3>
                <button class="btn btn-light" type="submit"> Yes, delete </button>
                <a href="{% url 'groups:groups-list' %}" class="btn btn-secondary"> No </a>
            </form>
        </div>

    </div>
{% endblock %}

templates/groups/channel_detail.html
{% extends "base.html" %}
{% block title %}
	<title>{{ channel.title }}</title>
{% endblock %}
{% block content %}
	<div class="container">
        <div class="align-items-center d-flex m-3">
            {% if channel.channel_picture %}
            <img src="{{ channel.channel_picture.url }}" alt="Profile Picture" class="me-3"
                 style="border-radius: 50%; width: 200px; height:200px; border: 2px grey solid">
            {% endif %}
            <div>
                <h2>{{ channel.title }}</h2>
                <h5>{{ channel.description }}</h5>
            </div>
        </div>
    <form action="{% url "groups:channel-join" pk=channel.pk %}" method="POST">
        {% csrf_token %}
        {{ joining.as_div }}
        <button type="submit" class="btn btn-danger">Join</button>
        {% if current_viewer.is_admin == True %}
            <a href="{% url "groups:channel-create-post" pk=channel.pk %}" class="ms-2 btn btn-primary">Create Post</a>
        {% endif %}
    </form>
        <a href="{% url "groups:viewers-list" pk=channel.pk %}" class="btn btn-light">Viewers</a>
    <h3 class="mt-5">Posts</h3>
    {% for post in posts %}
    {% include "post.html" %}
    {% endfor %}
    </div>
{% endblock %}

templates/groups/channels_list.html
{% extends "base.html" %}
{% block title %}
    <title>Channels List</title>
{% endblock %}
{% block content %}
    <div class="container">
        <a href="{% url "groups:channel-create" %}"class="btn btn-primary mb-3">Create Channel</a>
        {% for channel in channels %}
            <div class="card" style="width: 18rem;">
                <div class="card-body">
                    <h5 class="card-title">{{ channel.title }}</h5>
                    <p class="card-text">{{ channel.description }}</p>
                    <a href="{% url "groups:channel-detailed" pk=channel.pk %}" class="stretched-link"></a>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

templates/groups/group_creation_page.html
{% extends "base.html" %}
{% block title %}
	<title>Group Creation</title>
{% endblock %}
{% block content %}
	<div class="container">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_div }}
            <button type="submit" class="btn btn-success">Create Group</button>
        </form>
    </div>
{% endblock %}

templates/groups/group_delete_confirmation.html
{% extends "base.html" %}
{% block title %}
    <title>Delete Confirmation</title>
{% endblock %}
{% block content %}
    <div class="container">
        {% include 'alerts.html' %}
        <div class="d-flex justify-content-center align-items-center">
            <form method="post" class="">
                {% csrf_token %}
                <h3>Are you sure?</h3>
                <button class="btn btn-light" type="submit"> Yes, delete </button>
                <a href="{% url 'groups:groups-list' %}" class="btn btn-secondary"> No </a>
            </form>
        </div>

    </div>
{% endblock %}

templates/groups/group_detailed.html
{% extends "base.html" %}
{% block title %}
	<title>{{ group.title }}</title>
{% endblock %}
{% block content %}
	<div class="container">
        <div class="align-items-center d-flex m-3">
            {% if group.group_picture %}
            <img src="{{ group.group_picture.url }}" alt="Profile Picture" class="me-3"
                 style="border-radius: 50%; width: 200px; height:200px; border: 2px grey solid">
            {% endif %}
        <div>
            <h2>{{ group.title }}</h2>
            <h5>{{ group.description }}</h5>
        </div>   
        </div>
        <form action="{% url "groups:group-join" pk=group.pk %}" method="POST">
            {% csrf_token %}
            {{ join_form.as_div }}
            <button type="submit" class="btn btn-danger">Join</button>
            <a href="{% url "groups:group-create-post" pk=group.pk %}" class="btn btn-primary ms-2">Create Post</a>
        </form>
        <a href="{% url "groups:members-list" pk=group.pk %}" class="btn btn-light mt-3">Members</a>
    <h3 class="mt-5">Posts</h3>
    {% for post in posts %}
    {% include "post.html" %}
    {% endfor %}
    </div>
{% endblock %}

templates/groups/group_leaving_confirmation.html
{% extends "base.html" %}
{% block title %}
    <title>Delete Confirmation</title>
{% endblock %}
{% block content %}
    <div class="container">
        {% include 'alerts.html' %}
        <div class="d-flex justify-content-center align-items-center">
            <form method="post" class="">
                {% csrf_token %}
                <h3>Are you sure?</h3>
                <button class="btn btn-light" type="submit"> Yes, leave </button>
                <a href="{% url 'groups:group-detailed' pk=group_pk %}" class="btn btn-secondary"> No </a>
            </form>
        </div>

    </div>
{% endblock %}

templates/groups/groups_list.html
{% extends "base.html" %}
{% block title %}
	<title>Groups List</title>
{% endblock %}
{% block content %}
	<div class="container">
    <a href="{% url "groups:group-create" %}" class="btn btn-primary mb-3">Create Group</a>
    <div class="row">
    {% for group in groups %}
        <div class="col-6 col-md-4">
        <div class="card mb-3" style="width: 18rem;">
          <div class="card-body">
            <h5 class="card-title">{{ group.title }}</h5>
            <p class="card-text">{{ group.description }}</p>
            <a href="{% url "groups:group-detailed" pk=group.pk %}" class="stretched-link"></a>
          </div>
        </div>
        </div>
    {% endfor %}
    </div>
    </div>
{% endblock %}

templates/groups/members_list_view.html
{% extends "base.html" %}
{% block title %}
	<title>Members of {{ members.first.group }} group</title>
{% endblock %}
{% block content %}
	<div class="container">
    <div class="row">
    {% for member in members %}
        <div class="col-12 col-md-4">
            <div class="card mt-3">
                <div class="d-flex align-items-center justify-content-center">
                    {% if member.user.pfp %}
                        <img src="{{ member.user.pfp.url }}" alt="Profile Picture" class="m-3"
                             style="border-radius: 50%; width: 200px; height:200px; border: 2px grey solid">
                    {% endif %}
                    <h3 class="card-title">{{ member.user.username }}</h3>
                    <a href="{% url "profile:profile-detailed" pk=member.user.pk %}" class="stretched-link"></a>
                </div>
            </div>
        </div>
    {% endfor %}
    </div>
    </div>
{% endblock %}

templates/groups/viewers_list_view.html
{% extends "base.html" %}
{% block title %}
    <title>Viewers of {{ viewers.first.channel }} channel</title>
{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            {% for viewer in viewers %}
                <div class="col-12 col-md-4">
                    <div class="card mt-3">
                        <div class="d-flex align-items-center justify-content-center">
                            {% if viewer.user.pfp %}
                                <img src="{{ viewer.user.pfp.url }}" alt="Profile Picture" class="m-3"
                                     style="border-radius: 50%; width: 200px; height:200px; border: 2px grey solid">
                            {% endif %}
                            <h3 class="card-title">{{ viewer.user.username }}</h3>
                            <a href="{% url "profile:profile-detailed" pk=viewer.user.pk %}" class="stretched-link"></a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}