accounts/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path, include

from accounts import views

handler403 = views.custom_403_view

urlpatterns = [
    path('login/', views.CustomLoginView.as_view(), name='login'),
    path('logout/', views.CustomLogoutView.as_view(), name='logout'),
    path('register/', views.RegisterView.as_view(), name='register'),
]

app_name = 'accounts'

groups/urls.py
from django.urls import path
from groups import views
from posts import views as p_views

urlpatterns = [
    path('groups/', views.GroupsListView.as_view(), name='groups-list'),
    path('groups/create/', views.GroupCreateView.as_view(), name='group-create'),
    path('groups/<int:pk>/', views.GroupDetailView.as_view(), name='group-detailed'),
    path('groups/<int:pk>/create_post/', p_views.GroupPostCreateView.as_view(), name='group-create-post'),
    path('groups/<int:pk>/delete/', views.GroupDeleteView.as_view(), name='group-delete'),
    path('groups/<int:pk>/update/', views.GroupUpdateView.as_view(), name='group-update'),
    path('groups/<int:pk>/join/', views.MemberCreateView.as_view(), name='group-join'),
    path('groups/<int:pk>/leave/', views.MemberDeleteView.as_view(), name='group-leave'),
    path('channels/', views.ChannelListView.as_view(), name='channels-list'),
    path('channels/create/', views.ChannelCreateView.as_view(), name='channel-create'),
    path('channels/<int:pk>/update/', views.ChannelUpdateView.as_view(), name='channel-update'),
    path('channels/<int:pk>/delete/', views.ChannelDeleteView.as_view(), name='channel-delete'),
    path('channels/<int:pk>/', views.ChannelDetailView.as_view(), name='channel-detailed'),
    path('channels/<int:pk>/create_post/', p_views.ChannelPostCreateView.as_view(), name='channel-create-post'),
    path('channels/<int:pk>/join/', views.ViewerCreateView.as_view(), name='channel-join'),
    path("groups/<int:pk>/members/", views.MembersListView.as_view(), name='members-list'),
    path("channels/<int:pk>/viewers/", views.ViewersListView.as_view(), name='viewers-list'),

]

app_name = 'groups'

posts/urls.py
from django.urls import path
from posts import views


urlpatterns = [
    path("", views.PostsListView.as_view(), name="posts-list"),
    path("<int:pk>/", views.PostDetailView.as_view(), name="post-detailed"),
    path("<int:pk>/delete/", views.PostDeleteView.as_view(), name="delete-post"),
    path("<int:pk>/update/", views.PostUpdateView.as_view(), name="update-post"),
    path("<int:pk>/like/", views.LikeCreateView.as_view(), name="liking-post"),
    path("<int:pk>/comment/", views.CommentCreateView.as_view(), name="commenting-post"),
    path("<int:pk>/comment/delete/", views.CommentDeleteView.as_view(), name="comment-delete"),
    path("<int:pk>/comment/update/", views.CommentUpdateView.as_view(), name="comment-update"),
    path("<int:pk>/like/delete/", views.LikeDeleteView.as_view(), name="like-delete"),
    path("<int:pk>/repost/", views.RepostCreateView.as_view(), name="repost-create"),
    path("<int:pk>/repost/delete", views.RepostDeleteView.as_view(), name="repost-delete"),

]


app_name = "posts"

profiles/urls.py
from django.urls import path
from profiles import views
from posts import views as p_view


urlpatterns = [
    path('<int:pk>/', views.ProfileDetailView.as_view(), name="profile-detailed"),
    path("update/", views.ProfileUpdateView.as_view(), name="profile-update"),
    path("create_post/", p_view.ProfilePostCreateView.as_view(), name="create-post"),
    path("my_profile/", views.MyProfileDetailView.as_view(), name="my-profile"),
    path("<int:pk>/subscribe/", views.SubscriptionCreateView.as_view(), name="subscribe"),
    path("<int:pk>/unsubscribe/", views.SubscriptionDeleteView.as_view(), name="unsubscribe"),
    path("<int:pk>/send_friendrq/", views.FriendRequestCreateView.as_view(), name="friendrq"),
    path("<int:pk>/create_friendship/", views.FriendshipCreateView.as_view(), name="friendship"),
    path("<int:pk>/delete_friendrq/", views.FriendRequestDeleteView.as_view(), name="friendreq-delete"),
    path("users/", views.ProfilesListView.as_view(), name="profiles-list"),
    path("<int:pk>/delete_friendship/", views.FriendshipDeleteView.as_view(), name="friendship-delete"),

]

app_name = "profile"

social_media/urls.py
from django.contrib import admin
from django.urls import path, include
from social_media import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('posts.urls')),
    path('profile/', include('profiles.urls')),
    path('requests/', include('requests.urls')),
    path('groups_and_channels/', include('groups.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profiles/models.py
from django.db import models
from accounts.models import User

# Create your models here.


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="profile")
    pfp = models.ImageField(upload_to="users_pfp")
    username = models.CharField(max_length=80)
    bio = models.CharField(max_length=500, null=True, blank=True)
    status = models.CharField(max_length=60, null=True, blank=True)
    banner = models.ImageField(upload_to="users_banners", null=True, blank=True)

    def __str__(self):
        return self.username


class Friendship(models.Model):
    user1 = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name="friends_from")
    user2 = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name="friends_to")

    class Meta:
        unique_together = ("user1", "user2")

    def __str__(self):
        return f"{self.user1.username} is friends with {self.user2.username}"


class Subscriber(models.Model):
    subscriber = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name="subscriptions")
    account = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name="subscribers")

    def __str__(self):
        return f"{self.subscriber.username} subscribed to {self.account.username}"

posts/forms.py
from django import forms

from posts.models import Post, Like, Comment, Repost


class PostCreationForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["title", "description", "media"]

    def __init__(self, *args, **kwargs):
        super(PostCreationForm, self).__init__(*args, **kwargs)

        for field in self.fields:
            self.fields[field].widget.attrs.update({'class': "form-control mb-2"})

        self.fields["media"].widget.attrs.update({'class': "form-control mb-2", "type": "file"})


class PostUpdateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["title", "description"]

    def __init__(self, *args, **kwargs):
        super(PostUpdateForm, self).__init__(*args, **kwargs)

        for field in self.fields:
            self.fields[field].widget.attrs.update({'class': "form-control mb-2"})


class LikeCreationForm(forms.ModelForm):
    class Meta:
        model = Like
        fields = []


class CommentCreationForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["content"]
        widgets = {
            "content": forms.Textarea(attrs={'class': 'form-control mb-2'}),
        }


class RepostCreationForm(forms.ModelForm):
    class Meta:
        model = Repost
        fields = ["text"]
        widgets = {
            "text": forms.Textarea(attrs={'class': 'form-control mb-2'}),
        }

profiles/forms.py
from django import forms
from profiles.models import Profile, Subscriber, Friendship
from requests.models import FriendRequest


class ProfileCreationForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['pfp', 'username', 'bio', 'status', 'banner']

    def __init__(self, *args, **kwargs):
        super(ProfileCreationForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({'class': "form-control mb-2"})

        self.fields["pfp"].widget.attrs.update({'class': "form-control mb-2", 'type': "file"})
        self.fields["banner"].widget.attrs.update({'class': "form-control mb-2", 'type': "file"})


class SubscriptionCreationForm(forms.ModelForm):
    class Meta:
        model = Subscriber
        fields = []


class FriendRequestCreationForm(forms.ModelForm):
    class Meta:
        model = FriendRequest
        fields = []


class FriendshipCreationForm(forms.ModelForm):
    class Meta:
        model = Friendship
        fields = []


class SearchForm(forms.Form):
    search = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control mb-2'}), required=False,
                             label="Search by username")

posts/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ObjectDoesNotExist, PermissionDenied
from django.db import models
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView

from groups.models import Group, Channel
from posts.forms import PostCreationForm, PostUpdateForm, LikeCreationForm, CommentCreationForm, RepostCreationForm
from posts.models import Post, Comment, Like, Repost
from posts.mixins import UserIsOwnerMixin, ObjectExistMixin, UserIsNotLikeOwnerMixin, UsersActionMixin, \
    UserIsNotOwnerMixin
from profiles.models import Profile


# Create your views here.


class PostsListView(ListView):
    model = Post
    paginate_by = 10
    context_object_name = "posts"
    template_name = "posts/posts_list.html"

    def get_queryset(self):
        queryset = super(PostsListView, self).get_queryset()
        try:
            profile = self.request.user.profile
        except AttributeError:
            return queryset
        groups = Group.objects.filter(members__user=profile)
        channels = Channel.objects.filter(viewers__user=profile)
        friends = Profile.objects.filter(models.Q(friends_from__user1=profile) | models.Q(friends_to__user2=profile))
        subscriptions = Profile.objects.filter(subscriptions__subscriber=profile)

        posts = Post.objects.filter(
            models.Q(group__in=groups) | models.Q(channel__in=channels) | models.Q(profile__in=friends) | models.Q(profile__in=subscriptions)).distinct()

        return posts


class PostDetailView(DetailView):
    model = Post
    context_object_name = "post"
    template_name = "posts/post_detailed.html"

    def get_watched_post(self):
        post_pk = self.kwargs.get("pk")

        return get_object_or_404(Post, pk=post_pk)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["liking_form"] = LikeCreationForm()
        context["comment_form"] = CommentCreationForm()
        context["repost_form"] = RepostCreationForm()
        context["comments"] = get_object_or_404(Post, pk=self.kwargs.get("pk")).comments_on_post.all()
        if self.request.user.is_authenticated:
            context["repost"] = self.request.user.profile.reposts.filter(post=self.get_watched_post())
            context["like"] = self.request.user.profile.likes.filter(post=self.get_watched_post())
        context["likes_count"] = self.object.likes.count()
        context["repost_count"] = self.object.reposts.count()

        return context


class ProfilePostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    success_url = reverse_lazy("profile:my-profile")
    form_class = PostCreationForm
    template_name = "posts/post_creation_form.html"

    def form_valid(self, form):
        form.instance.created_by = self.request.user.profile
        form.instance.profile = self.request.user.profile
        form.instance.type = "profile"

        return super().form_valid(form)


class GroupPostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    form_class = PostCreationForm
    template_name = "posts/post_creation_form.html"

    def form_valid(self, form):
        form.instance.created_by = self.request.user.profile
        form.instance.group = get_object_or_404(Group, pk=self.kwargs.get("pk"))
        form.instance.type = "group"

        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy("groups:group-detailed", kwargs={"pk": self.kwargs.get("pk")})


class ChannelPostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    form_class = PostCreationForm
    template_name = "posts/post_creation_form.html"

    def get_success_url(self):
        return reverse_lazy("groups:channel-detailed", kwargs={"pk": self.kwargs.get("pk")})

    def form_valid(self, form):
        form.instance.created_by = self.request.user.profile
        form.instance.channel = get_object_or_404(Channel, pk=self.kwargs.get("pk"))
        form.instance.type = "channel"

        return super().form_valid(form)


class PostDeleteView(LoginRequiredMixin, UserIsOwnerMixin, DeleteView):
    model = Post
    template_name = "posts/post_delete_confirmation.html"
    success_url = reverse_lazy("posts:posts-list")


class PostUpdateView(LoginRequiredMixin, UserIsOwnerMixin, UpdateView):
    model = Post
    form_class = PostUpdateForm
    context_object_name = "post"
    template_name = "posts/post_update_form.html"

    def get_success_url(self):
        return reverse_lazy("posts:post-detailed", kwargs={"pk": self.object.pk})


class LikeCreateView(LoginRequiredMixin, UserIsNotLikeOwnerMixin, ObjectExistMixin, CreateView):
    model = Like
    form_class = LikeCreationForm

    def get_post(self):
        post_pk = self.kwargs.get("pk")

        return get_object_or_404(Post, pk=post_pk)

    def get_success_url(self):
        return reverse_lazy("posts:post-detailed", kwargs={"pk": self.object.post.pk})

    def form_valid(self, form):
        form.instance.post = self.get_post()
        form.instance.user = self.request.user.profile

        return super().form_valid(form)


class LikeDeleteView(LoginRequiredMixin, UsersActionMixin, DeleteView):
    model = Like

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["post_pk"] = self.object.post.pk

        return context

    def get_post(self):
        post_pk = self.kwargs.get("pk")

        return get_object_or_404(Post, pk=post_pk)

    def get_success_url(self):
        return reverse_lazy("posts:post-detailed", kwargs={"pk": self.object.post.pk})


class CommentCreateView(LoginRequiredMixin, CreateView):
    model = Comment
    form_class = CommentCreationForm

    def get_post(self):
        post_pk = self.kwargs.get("pk")

        return get_object_or_404(Post, pk=post_pk)

    def get_success_url(self):
        return reverse_lazy("posts:post-detailed", kwargs={"pk": self.object.related_post.pk})

    def form_valid(self, form):
        form.instance.created_by = self.request.user.profile
        form.instance.related_post = self.get_post()

        return super().form_valid(form)


class CommentUpdateView(LoginRequiredMixin, UserIsOwnerMixin, UpdateView):
    model = Comment
    template_name = "posts/comment_update_form.html"
    form_class = CommentCreationForm

    def get_success_url(self):
        return reverse_lazy("posts:post-detailed", kwargs={"pk": self.object.related_post.pk})


class CommentDeleteView(LoginRequiredMixin, UserIsOwnerMixin, DeleteView):
    model = Comment
    template_name = "posts/comment_delete_confirmation.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["post_pk"] = self.object.related_post.pk

        return context

    def get_success_url(self):
        return reverse_lazy("posts:post-detailed", kwargs={"pk": self.object.related_post.pk})


class RepostCreateView(LoginRequiredMixin, CreateView):
    model = Repost
    form_class = RepostCreationForm

    def get_post(self):
        post_pk = self.kwargs.get("pk")

        return get_object_or_404(Post, pk=post_pk)

    def get_success_url(self):
        return reverse_lazy("posts:post-detailed", kwargs={"pk": self.object.post.pk})

    def form_valid(self, form):
        if self.request.user.profile == self.get_post().created_by:
            raise PermissionDenied("You can't repost your own post.")
        form.instance.user = self.request.user.profile
        form.instance.post = self.get_post()

        return super().form_valid(form)


class RepostDeleteView(LoginRequiredMixin, UsersActionMixin, DeleteView):
    model = Repost

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["post_pk"] = self.object.post.pk

        return context

    def get_post(self):
        post_pk = self.kwargs.get("pk")

        return get_object_or_404(Post, pk=post_pk)

    def get_success_url(self):
        return reverse_lazy("posts:post-detailed", kwargs={"pk": self.object.post.pk})

templates/alerts.html
{% if messages %}
  {% for message in messages %}
        <div{% if message.tags %} class="alert {{ message.tags }}"{% endif %} role="alert">
            {{ message }}
        </div>
  {% endfor %}
{% endif %}

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

      {% block title %}
    <title>Social Media</title>
      {% endblock %}

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
  </head>
  <body data-bs-theme="dark">
   <nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'posts:posts-list' %}">Social Media</a>
      <a href="{% url "groups:groups-list" %}" class="nav-link me-3 ">Groups</a>
      <a href="{% url "groups:channels-list" %}" class="nav-link me-3 ">Channels</a>
      <a href="{% url "profile:profiles-list" %}" class="nav-link me-3 ">Users</a>
    {% if user.is_staff %}
      <a href="/admin/" class="nav-link me-3 ">Admin Panel</a>
    {% endif %}
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      </ul>
     {% if request.user.is_authenticated %}
         <a href="{% url "profile:my-profile" %}" class="nav-link me-3">My Profile</a>
         <a href="{% url 'friendrq-list' %}" class="nav-link me-3">Friend Requests</a>
        <a href="{% url "profile:create-post" %}" class="btn btn-outline-light me-3 ">Create Post</a>
          <form action="{% url 'accounts:logout' %}" method="post">
            {% csrf_token %}
             <button type="submit" class="btn btn-outline-secondary">
                    Logout
              </button>
          </form>
        {% else %}
         <a href="{% url "accounts:login" %}" class="btn btn-outline-light">
                    Login
              </a>
     {% endif %}



    </div>
  </div>
</nav>
    <main  class="my-3">
        {% block content %}

        {% endblock %}
    </main>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

templates/post.html
<div class="card m-4" style="width: 50rem;">
    <div class="card-header d-flex justify-content-between">
        {% if post.profile %}
        <a class="h3 text-decoration-none" href="{% url "profile:profile-detailed" pk=post.profile.pk %}">{{ post.created_by.username }}</a>
        {% elif post.group %}
        <a class="h3 text-decoration-none" href="{% url "groups:group-detailed" pk=post.group.pk %}">{{ post.group.title }} (group)</a>
        {% elif post.channel %}
        <a class="h3 text-decoration-none" href="{% url "groups:channel-detailed" pk=post.channel.pk %}">{{ post.group.title }} (channel)</a>
        {% endif %}
        <span>{{ post.created_at|date:"d F" }}</span>
    </div>
    
  <div class="card-body">
      <a class="text-decoration-none text-white" href="{% url "posts:post-detailed" post.pk %}">
      {% if post.media %}
          <img src="{{ post.media.url }}" class="card-img-top img-fluid" alt="..." style="max-height: 500px">
      {% endif %}
    <h3 class="card-title mt-3">{{ post.title }}</h3>
      </a>
  </div>
</div>

templates/profile.html
<div class="col-12 col-md-6">
    <div class="card mt-3">
        <div class="d-flex align-items-center justify-content-center">
            {% if profile.pfp %}
                <img src="{{ profile.pfp.url }}" alt="Profile Picture" class="m-3"
                     style="border-radius: 50%; width: 200px; height:200px; border: 2px grey solid">
            {% endif %}
            <h3 class="card-title">{{ profile.username }}</h3>
            <a href="{% url "profile:profile-detailed" pk=profile.pk %}" class="stretched-link"></a>
        </div>
    </div>
</div>